### ISSUE TITLE
Plugin conflict when loading the blueprint

### ISSUE THREAD

**Issue by psiwczak** [cloudify-examples/simple-kubernetes-blueprint#2]
Hi,
I tried to install this blueprint with Cloudify v4.4.0-.dev1 and I get the "plugin conflict" error in aws-blueprint.yaml:

```
An error occurred on the server: 400: Invalid blueprint - Import failed: Could not merge 'plugins' due to conflict on 'diamond' 
  in: /opt/manager/resources/aws-blueprint-12480aab-97ba-47e0-b1a6-d1322a0f3791/aws-blueprint.yaml
  in line: 6, column: 0
  path: imports
  value: ['http://www.getcloudify.org/spec/cloudify/4.3/types.yaml', 'plugin:cloudify-diamond-plugin?version=1.3.8', 'plugin:cloudify-fabric-plugin?version=1.5.1', 'plugin:cloudify-utilities-plugin?version=1.5.0.1', 'imports/kubernetes.yaml', 'https://github.com/cloudify-cosmo/cloudify-aws-plugin/releases/download/1.5.1.2/plugin.yaml', 'imports/cloud-config.yaml']
```

Here are my plugin versions:
```
cloudify-azure-plugin 1.5.1
cloudify-fabric-plugin 1.5.1
cloudify-vsphere-plugin 2.3.0
cloudify-openstack-plugin 2.6.0
cloudify-aws-plugin 1.5.1.2
cloudify-utilities-plugin 1.5.0
cloudify-kubernetes-plugin 2.0.0
cloudify-gcp-plugin 1.4.0
cloudify-awssdk-plugin 1.2.0.3
cloudify-diamond-plugin 1.3.8
cloudify-utilities-plugin 1.5.0.1
```

How can I resolve it?

**Comment by EarthmanT** [comment]
The error itself would indicate that this plugin is being imported twice somewhere. However, according to the last line of the error message there are no merging conflicts.

This sounds like a bug in the development branch of Cloudify Manager that you are using (4.4.0-.dev1). The current version of this blueprint is only supported on Cloudify 4.3.

**Comment by psiwczak** [comment]
@EarthmanT Thank you very much for the answer. Will test against 4.3 and let you know the results in this thread

**Comment by psiwczak** [comment]
Hi,

Just checked against 4.3.0. The error persists. (please note I use the community edition installer rpm to install cloudify manager).

**Comment by EarthmanT** [comment]
Hi,
Please make sure that you have uploaded all of the plugins:

https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/releases/tag/2.1.0
https://github.com/cloudify-cosmo/cloudify-aws-plugin/releases/tag/1.5.1.2
https://github.com/cloudify-cosmo/cloudify-fabric-plugin/releases/tag/1.5.1
https://github.com/cloudify-cosmo/cloudify-diamond-plugin/releases/tag/1.3.8
https://github.com/cloudify-incubator/cloudify-utilities-plugin/releases/tag/1.5.0.1

You must upload the plugin yaml and the wagon together at the system resources plugin upload dialog box.

Afterwards, execute this from the CLI:

```shell
cfy install https://github.com/cloudify-examples/simple-kubernetes-blueprint/releases/download/cloudify-kubernetes-4.3-14/cloudify-kubernetes-4.3-14.tar.gz --blueprint-filename aws-blueprint.yaml --blueprint-id kube
```
